# Generated by Django 5.2.17 on 2026-10-04 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_seed_demo_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medication',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supportrequest',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='support_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient_name',
            field=models.CharField(blank=True, max_length=180, verbose_name='Имя пациента'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='phone',
            field=models.CharField(blank=True, max_length=32, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='supportrequest',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='supportrequest',
            name='name',
            field=models.CharField(blank=True, max_length=120, verbose_name='Имя'),
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('event', 'Событие'), ('certificate', 'Справка'), ('lab_result', 'Результат анализа'), ('study', 'Исследование'), ('visit_protocol', 'Протокол приёма')], max_length=24)),
                ('title', models.CharField(max_length=220, verbose_name='Название')),
                ('summary', models.TextField(blank=True, verbose_name='Описание')),
                ('occurred_at', models.DateTimeField(verbose_name='Дата события')),
                ('doctor_name', models.CharField(blank=True, max_length=180, verbose_name='Врач')),
                ('document_url', models.URLField(blank=True, verbose_name='Ссылка на документ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Запись медкарты',
                'verbose_name_plural': 'Медкарта',
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='Телефон')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('policy_number', models.CharField(blank=True, max_length=32, verbose_name='Номер полиса')),
                ('role', models.CharField(choices=[('patient', 'Пациент'), ('admin', 'Администратор')], default='patient', max_length=16)),
                ('avatar_background', models.PositiveSmallIntegerField(default=1, editable=False)),
                ('avatar_dino', models.PositiveSmallIntegerField(default=1, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль пациента',
                'verbose_name_plural': 'Профили пациентов',
            },
        ),
    ]
