# Generated by Django 5.2.17 on 2026-10-04 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_appointment_patient_medication_patient_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание приёма'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='diagnosis',
            field=models.TextField(blank=True, verbose_name='Диагноз'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='phone_number',
            field=models.CharField(blank=True, max_length=32, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='middle_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Отчество'),
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issuance_date', models.DateField(verbose_name='Дата выдачи')),
                ('illness_start', models.DateField(blank=True, null=True, verbose_name='Начало заболевания')),
                ('illness_end', models.DateField(blank=True, null=True, verbose_name='Окончание заболевания')),
                ('diagnosis', models.TextField(blank=True, verbose_name='Диагноз')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certificates', to='api.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Справка',
                'verbose_name_plural': 'Справки',
                'ordering': ['-issuance_date'],
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendations', models.TextField(blank=True, verbose_name='Рекомендации')),
                ('tests', models.TextField(blank=True, verbose_name='Исследования')),
                ('analyses', models.TextField(blank=True, verbose_name='Анализы')),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prescription', to='api.appointment')),
            ],
            options={
                'verbose_name': 'Назначение',
                'verbose_name_plural': 'Назначения',
            },
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, verbose_name='Препарат')),
                ('dose', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Доза')),
                ('days', models.PositiveIntegerField(verbose_name='Дней курса')),
                ('days_left', models.PositiveIntegerField(verbose_name='Дней осталось')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drugs', to='api.prescription')),
            ],
            options={
                'verbose_name': 'Препарат в назначении',
                'verbose_name_plural': 'Препараты в назначениях',
            },
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issuance_date', models.DateField(verbose_name='Дата выдачи')),
                ('expiration_date', models.DateField(verbose_name='Действительно до')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referrals', to='api.doctor')),
            ],
            options={
                'verbose_name': 'Направление',
                'verbose_name_plural': 'Направления',
                'ordering': ['-issuance_date'],
            },
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_and_time', models.DateTimeField(verbose_name='Дата и время')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступен')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='api.doctor')),
            ],
            options={
                'verbose_name': 'Слот приёма',
                'verbose_name_plural': 'Слоты приёма',
                'ordering': ['date_and_time'],
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='slot',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appointment', to='api.slot'),
        ),
        migrations.AddConstraint(
            model_name='slot',
            constraint=models.UniqueConstraint(fields=('doctor', 'date_and_time'), name='unique_doctor_date_and_time'),
        ),
    ]
