# Generated by Django 5.2.17 on 2026-10-04 17:40

from django.db import migrations, models


def split_doctor_names(apps, schema_editor):
    Doctor = apps.get_model("api", "Doctor")
    for doctor in Doctor.objects.all().iterator():
        parts = doctor.full_name.split()
        if parts:
            doctor.name = parts[0]
        if len(parts) == 2:
            doctor.surname = parts[1]
        elif len(parts) >= 3:
            doctor.middle_name = " ".join(parts[1:-1])
            doctor.surname = parts[-1]
        doctor.save(update_fields=["name", "surname", "middle_name"])


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_require_appointment_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='middle_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Отчество'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='surname',
            field=models.CharField(blank=True, max_length=150, verbose_name='Фамилия'),
        ),
        migrations.RunPython(split_doctor_names, migrations.RunPython.noop),
    ]
