# Generated by Django 5.2.17 on 2026-10-04 18:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_doctor_middle_name_doctor_name_doctor_surname'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntakeSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Активен'), ('completed', 'Завершён'), ('urgent', 'Требует срочной помощи')], default='active', max_length=16)),
                ('urgency', models.CharField(choices=[('low', 'Низкая'), ('consultation', 'Нужна консультация'), ('urgent', 'Срочно')], default='low', max_length=16)),
                ('summary', models.TextField(blank=True, verbose_name='Резюме анамнеза')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intake_sessions', to=settings.AUTH_USER_MODEL)),
                ('specialty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intake_sessions', to='api.specialty')),
            ],
            options={
                'verbose_name': 'Сессия анамнеза',
                'verbose_name_plural': 'Сессии анамнеза',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='IntakeMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Пациент'), ('assistant', 'Ассистент')], max_length=16)),
                ('content', models.TextField(verbose_name='Сообщение')),
                ('structured_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.intakesession')),
            ],
            options={
                'verbose_name': 'Сообщение анамнеза',
                'verbose_name_plural': 'Сообщения анамнеза',
                'ordering': ['created_at'],
            },
        ),
    ]
